// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ok.proto

package haha

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Haha int32

const (
	Haha_UNKNOWN Haha = 0
	Haha_HTTP    Haha = 1
	Haha_GRPC    Haha = 2
)

var Haha_name = map[int32]string{
	0: "UNKNOWN",
	1: "HTTP",
	2: "GRPC",
}

var Haha_value = map[string]int32{
	"UNKNOWN": 0,
	"HTTP":    1,
	"GRPC":    2,
}

func (x Haha) String() string {
	return proto.EnumName(Haha_name, int32(x))
}

func (Haha) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9026e66a375a14b8, []int{0}
}

type OK struct {
	Haha                 Haha     `protobuf:"varint,1,opt,name=haha,proto3,enum=haha.Haha" json:"haha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OK) Reset()         { *m = OK{} }
func (m *OK) String() string { return proto.CompactTextString(m) }
func (*OK) ProtoMessage()    {}
func (*OK) Descriptor() ([]byte, []int) {
	return fileDescriptor_9026e66a375a14b8, []int{0}
}
func (m *OK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OK.Unmarshal(m, b)
}
func (m *OK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OK.Marshal(b, m, deterministic)
}
func (m *OK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OK.Merge(m, src)
}
func (m *OK) XXX_Size() int {
	return xxx_messageInfo_OK.Size(m)
}
func (m *OK) XXX_DiscardUnknown() {
	xxx_messageInfo_OK.DiscardUnknown(m)
}

var xxx_messageInfo_OK proto.InternalMessageInfo

func (m *OK) GetHaha() Haha {
	if m != nil {
		return m.Haha
	}
	return Haha_UNKNOWN
}

func init() {
	proto.RegisterEnum("haha.Haha", Haha_name, Haha_value)
	proto.RegisterType((*OK)(nil), "haha.OK")
}

func init() { proto.RegisterFile("ok.proto", fileDescriptor_9026e66a375a14b8) }

var fileDescriptor_9026e66a375a14b8 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xcf, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x48, 0xcc, 0x48, 0x54, 0x52, 0xe1, 0x62, 0xf2, 0xf7,
	0x16, 0x92, 0xe3, 0x02, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xb8, 0xf4, 0x40, 0x1c,
	0x3d, 0x8f, 0xc4, 0x8c, 0xc4, 0x20, 0xb0, 0xb8, 0x96, 0x3a, 0x17, 0x0b, 0x88, 0x27, 0xc4, 0xcd,
	0xc5, 0x1e, 0xea, 0xe7, 0xed, 0xe7, 0x1f, 0xee, 0x27, 0xc0, 0x20, 0xc4, 0xc1, 0xc5, 0xe2, 0x11,
	0x12, 0x12, 0x20, 0xc0, 0x08, 0x62, 0xb9, 0x07, 0x05, 0x38, 0x0b, 0x30, 0x39, 0x89, 0x47, 0x89,
	0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xe7, 0x67, 0x83, 0x10, 0xc8,
	0x84, 0x24, 0x36, 0xb0, 0xa5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0xda, 0x41, 0x9d,
	0x80, 0x00, 0x00, 0x00,
}
